replicaCount: 1

image:
  repository: hqcbaregistry.azurecr.io/nvault-control-live
  tag: "0017c50a95d2276efe9354a7f91336857ad9386e"
  pullPolicy: IfNotPresent

env:
  NODE_ENV: development
  PORT: 5050
  REDIS_HOST: "redis-15090.c85.us-east-1-2.ec2.cloud.redislabs.com"
  REDIS_PORT: 15090
  BASE_URL: http://66.29.138.198:30128/
  SRV: rdr
  RATE_LIMITING_ENABLED: "false"
  CLOUDINARY_CLOUD_NAME: "dshfdqw0u"
  USE_BREVO: "true"
  BREVO_SMTP_HOST: smtp-relay.brevo.com
  BREVO_SMTP_PORT: 587
  MAIL_FROM_NAME: "WeDrive"
  MAIL_FROM_ADDRESS: "hq.wedrive@gmail.com"
  TEST_EMAIL_TO: "temitopejulius9@gmail.com"
  FIREBASE_SERVICE_ACCOUNT_PATH: "./wedrive-korra-firebase-adminsdk-fbsvc-6dfc2743c3.json"
  KRELTIX_BASE_URL: "https://kreltix.com/api/v1"
  KRELTIX_API_KEY: "sk_NdajtAM_al2VnfQdggt9LQS9Fr7UbDizNs9SP6ZGT_g"

secretEnv:
  - name: BREVO_SMTP_PASS
    secretName: control-live
    key: BREVO_SMTP_PASS
  - name: BREVO_SMTP_USER
    secretName: control-live
    key: BREVO_SMTP_USER
  - name: REDIS_PASSWORD
    secretName: control-live
    key: REDIS_PASSWORD
  - name: DATABASE_URL
    secretName: control-live
    key: DATABASE_URL
  - name: CLOUDINARY_API_SECRET
    secretName: control-live
    key: CLOUDINARY_API_SECRET
  - name: CLOUDINARY_API_KEY
    secretName: control-live
    key: CLOUDINARY_API_KEY
  - name: JWT_SECRET
    secretName: control-live
    key: JWT_SECRET
  - name: RABBITMQ_URL
    secretName: control-live
    key: RABBITMQ_URL    
  - name: GOOGLE_MAPS_API_KEY
    secretName: control-live
    key: GOOGLE_MAPS_API_KEY  


service:
  type: NodePort
  port: 5050
  targetPort: 5050
  nodePort: 30128

imagePullSecrets:
  - acr-secret2

