replicaCount: 1

image:
  repository: hqcbaregistry.azurecr.io/nvault-control-live
  tag: "0662b90da2d2dec3ed00c58d188549b499f52c01"
  pullPolicy: IfNotPresent

env:
  DATABASE_URL: "mongodb+srv://gidicart:korra_atkd1845@gidicart-cluster0.2qks9.mongodb.net/?appName=Gidicart-Cluster0"
  JWT_SECRET: 39ehdne89yr390ru3rdnfr7uy4r92ejsjo9e8ie
  NODE_ENV: development
  PORT: 5050
  REDIS_HOST: 66.29.138.198
  REDIS_PASSWORD: St3@dy911
  REDIS_PORT: 30379
  RABBITMQ_URL: amqp://neptune:St%403dy911@66.29.138.198:30672
  BASE_URL: http://66.29.138.198:30128/
  SRV: rdr

secretEnv:
  - name: NVAULT_GOOGLE_CRED
    secretName: central-service
    key: NVAULT_GOOGLE_CRED
  - name: ETOKEN_APP_GOOGLE_CRED
    secretName: central-service
    key: ETOKEN_APP_GOOGLE_CRED
  - name: WHATSAPP_ACCESS_TOKEN
    secretName: central-service
    key: WHATSAPP_ACCESS_TOKEN
  - name: DB_URL
    secretName: central-service
    key: DB_URL

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30128

imagePullSecrets:
  - acr-secret2

