replicaCount: 1

image:
  repository: hqcbaregistry.azurecr.io/nvault-control-live
  tag: "27e90fcbc94d6b53f6706699f3dc7780cf433a2c"
  pullPolicy: IfNotPresent

env:
  DATABASE_URL: "mongodb+srv://gidicart:korra_atkd1845@gidicart-cluster0.2qks9.mongodb.net/?appName=Gidicart-Cluster0"
  JWT_SECRET: 39ehdne89yr390ru3rdnfr7uy4r92ejsjo9e8ie
  NODE_ENV: development
  PORT: 5050
  REDIS_HOST: redis-15090.c85.us-east-1-2.ec2.cloud.redislabs.com
  REDIS_PASSWORD: izVg1gZB9tvsioPMSuihG0Hw6MWlVd8k
  REDIS_PORT: 15090
  SRV: rdr

secretEnv:
  - name: NVAULT_GOOGLE_CRED
    secretName: central-service
    key: NVAULT_GOOGLE_CRED
  - name: ETOKEN_APP_GOOGLE_CRED
    secretName: central-service
    key: ETOKEN_APP_GOOGLE_CRED
  - name: WHATSAPP_ACCESS_TOKEN
    secretName: central-service
    key: WHATSAPP_ACCESS_TOKEN
  - name: DB_URL
    secretName: central-service
    key: DB_URL

service:
  type: NodePort
  port: 5050
  targetPort: 5050
  nodePort: 30128

imagePullSecrets:
  - acr-secret2

